/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.GestorUsuarios;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Timer;


/**
 *
 * @author jhery
 */
public class Login extends javax.swing.JFrame {
    private final GestorUsuarios gestorUsuarios;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.gestorUsuarios = new GestorUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelInicar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(850, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(810, 500));
        bg.setPreferredSize(new java.awt.Dimension(850, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Biblioteca (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(4000, 520));
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 320, 520));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelUsuario.setText("Usuario:");
        bg.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        labelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelContraseña.setText("Contraseña:");
        bg.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        labelInicar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelInicar.setText("Iniciar Sesión");
        bg.add(labelInicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 10));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setText("Ingrese su contraseña");
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        bg.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 350, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 256, 290, 10));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setText("Ingrese su usuario");
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        bg.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 350, -1));

        btnLogin.setBackground(new java.awt.Color(0, 51, 204));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        bg.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 150, 50));
        bg.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
      
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());


        Usuario usuarioValidado = gestorUsuarios.validarCredenciales(username, password);

        if (usuarioValidado != null) {
            // Credenciales validas
            String mensaje = "¡Bienvenido, " + usuarioValidado.getUsername() + " (" + usuarioValidado.getRol() + ")!";
            mostrarMensajeTemporal(mensaje,false,1500);
            limpiarCampos();
            Timer timerTransicion = new Timer(1500, (ActionEvent e) -> {
                // Se ejecutara despues del timer
                Login.this.dispose();
                PanelGestion panelGestion = new PanelGestion();
                panelGestion.setVisible(true);
                //ControladorBiblioteca controladorBiblioteca = new ControladorBiblioteca(vistaBiblioteca);
                //vistaBiblioteca.setVisible(true);
            });
            timerTransicion.setRepeats(false);
            timerTransicion.start();

        } else {
            // Credenciales invalidas
            mostrarMensajeTemporal("Usuario o contraseña incorrectos.", true, 2000);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    
    public void mostrarMensajeTemporal(String mensaje, boolean esError, int delay) {
        lblMensaje.setText(mensaje);
        lblMensaje.setForeground(esError ? Color.RED : Color.BLUE); // Azul para exito
        
        Timer timer = new Timer(delay, (ActionEvent e) -> {
            lblMensaje.setText("");
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    
    public void limpiarCampos() {
        txtUsername.setText("");
        txtPassword.setText("");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelInicar;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
